schema:
  - ./client/schema.graphql
  - ./client/src/apollo/localSchema.graphql
documents: ./client/src/**/*.{ts,tsx}
extensions:
  languageService:
    # Use graphql-eslint to validate schemas instead
    enableValidation: false
