cors:
  allow_any_origin: true
headers:
  subgraphs:
    spotify:
      request:
        - propagate:
            matching: 'authorization'
        - propagate:
            matching: 'x-graphos-id'
    playback:
      request:
        - propagate:
            matching: 'authorization'
        - propagate:
            matching: 'x-graphos-id'
include_subgraph_errors:
  all: true
sandbox:
  enabled: true
supergraph:
  introspection: true
  listen: 0.0.0.0:4000
homepage:
  enabled: false
apq:
  enabled: false
#####################
# Enable to use persisted queries. You must set the env var
# `APOLLO_ROVER_DEV_ROUTER_VERSION=1.25.0-alpha.0` for this to work.
#####################
# preview_persisted_queries:
#   enabled: true

#####################
# You must have an enterprise account or enterprise trial to run the Apollo Router locally.
#####################
# # Uncomment 'passthrough' to try Websockets at the /ws route using graphql-ws
# subscription:
#   mode:
#     passthrough:
#       all:
#         path: /ws

# # Uncomment 'preview_callback' to try HTTP callback protocal at the /graphql
# # https://www.apollographql.com/docs/router/executing-operations/subscription-callback-protocol
subscription:
  mode:
    preview_callback:
      public_url: http://127.0.0.1:4000 # The router's public URL
      listen: 0.0.0.0:${env.PORT:-4000} # The IP address and port the router will listen on for subscription callbacks
      path: /callback # The path of the router's callback endpoint
      subgraphs: # The list of subgraphs that use the HTTP callback protocol
        - playback
