cors:
  allow_any_origin: true
headers:
  subgraphs:
    spotify:
      request:
        - propagate:
            matching: "Authentication"
    playback:
      request:
        - propagate:
            matching: "Authentication"
include_subgraph_errors:
  all: true
sandbox:
  enabled: true
supergraph:
  introspection: true
  listen: 127.0.0.1:4000
homepage:
  enabled: false
subscription:
  mode:
    passthrough:
      subgraphs:
        playback:
          path: /ws