apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  selector:
    app: router
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  name: router
  labels:
    app: router
spec:
  containers:
    - name: router
      image: router:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 4000
      env:
        - name: APOLLO_KEY
          valueFrom:
            secretKeyRef:
              name: graphos
              key: APOLLO_KEY
        - name: APOLLO_GRAPH_REF
          valueFrom:
            secretKeyRef:
              name: graphos
              key: APOLLO_GRAPH_REF
      volumeMounts:
        - mountPath: /dist/supergraph.graphql
          subPath: supergraph.graphql
          name: supergraph-schema
    - name: coprocessor
      image: coprocessor:latest
      imagePullPolicy: Never
      ports:
          - containerPort: 4100
      env:
        - name: RUST_LOG
          value: info
  volumes:
    - name: supergraph-schema
      configMap:
        name: supergraph-schema