name: 'Pull Request'
on:
  pull_request:
    paths:
      -  'client/**'
      - '.github/workflows/client_pull_request.yaml'

jobs:
  client-check:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install --prefix=client
      - name: Run ESLint
        run: npm run lint --prefix=client
