name: 'Pull Request'
on:
  pull_request:
    paths:
      -  'client/**'
      - '.github/workflows/client_pull_request.yaml'

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run ESLint
        run: cd client && npm install && npm run lint

  typescript-client:
    runs-on: ubuntu-latest
    name: Check TypeScript (client)
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Check client
        run: cd client && npm install && npm run build