name: Playback Subgraph Workflows
on:
  pull_request:
    paths:
      - 'subgraphs/playback/**'
      - '.github/workflows/playback_checks.yaml'

jobs:
  check_playback_schema:
    name: Check Playback Subgraph Schema with GraphOS
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - if: env.APOLLO_KEY != ''
        run: rover subgraph check Spotify-tb7du2@prod --schema ./subgraphs/playback/schema.graphql --name playback
  check_playback_builds:
    name: Check server compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install --prefix=subgraphs/playback
      - name: Check server compiles
        run: npm run build --prefix=subgraphs/playback
  check_playback_typescript:
    name: Check TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install --prefix=subgraphs/playback
      - name: Check TypeScript
        run: npm run lint:types --prefix=subgraphs/playback
