name: Publish playback schema
on:
  push:
    branches:
      - main
    paths:
      - 'subgraphs/playback/**'
      - '.github/workflows/playback_publish.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  publish_playback_schema:
    name: Publish Playback schema to GraphOS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish Schema
        run: rover subgraph publish $APOLLO_GRAPH_REF --schema ./subgraphs/playback/schema.graphql --name playback
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
          APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
          APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
