name: Playback Subgraph Workflows
on: 
  pull_request:
    paths:
      -  'subgraphs/playback/**'
      - '.github/workflows/playback_checks.yaml'

jobs:
  check_playback_schema:
    name: Check Playback Subgraph Schema with GraphOS
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Check server compiles
        run: npm run build --prefix=subgraphs/playback
      - if: env.APOLLO_KEY != ''
        run: rover subgraph check Spotify-tb7du2@prod --schema ./subgraphs/playback/schema.graphql --name playback