name: Playback Subgraph Workflows
on:
  pull_request:
    paths:
      - 'subgraphs/playback/**'
      - '.github/workflows/playback_checks.yaml'

jobs:
  check_playback_schema:
    name: Check Playback Subgraph Schema with GraphOS
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - if: env.APOLLO_KEY != ''
        run: rover subgraph check $APOLLO_GRAPH_REF --schema ./subgraphs/playback/schema.graphql --name playback
        env:
          APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  check_playback_builds:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install -w playback-subgraph
      - name: Check server compiles
        run: npm run build -w playback-subgraph
      - name: Run unit tests
        run: npm run test -w playback-subgraph
