name: 'Pull Request (all)'
on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run Lint
        run: npm run lint
