name: Spotify Subgraph Workflows
on:
  pull_request:
    paths:
      - 'subgraphs/spotify/**'
      - '.github/workflows/spotify_checks.yaml'

jobs:
  check_spotify_schema:
    name: Check Spotify Subgraph Schema with GraphOS
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_GRAPH_REF: ${{ secrets.APOLLO_GRAPH_REF }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - if: env.APOLLO_KEY != ''
        run: rover subgraph check $APOLLO_GRAPH_REF --schema ./subgraphs/spotify/schema.graphql --name spotify
        env:
          APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  check_spotify_builds:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install --prefix=subgraphs/spotify
      - name: Check server compiles
        run: npm run build --prefix=subgraphs/spotify
      - name: Run unit tests
        run: npm run test --prefix=subgraphs/spotify
  check_spotify_typescript:
    name: Check TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install --prefix=subgraphs/spotify
      - name: Check TypeScript
        run: npm run lint:types --prefix=subgraphs/spotify
